### ISSUE TITLE
Auto commit bot 🤔🏴‍☠️

### ISSUE THREAD

**Issue by sudo-do** [Limitly/Free-Copilot#110]
Why dont we make an auto commit bot to spam the repo 🏴‍☠️🏴‍☠️🏴‍☠️

**Comment by InimicalPart** [comment]
We think that stars are the metric that count. A bot might be able to spam the repository, but it will not benefit us in any way, and it will also sabotage other metrics like the amount of commits. We also much rather prefer having people do it cause then we can see how much traffic the repository is getting.

**Comment by mariuszste** [comment]
star bot :trollface: 

I mean, it's doable, it will cost a bit in captcha solutions but making a few hundred or even few thousand github accounts isn't that hard if you know what you're doing ;) Still way cheaper than a single month of copilot though.

**Comment by InimicalPart** [comment]
I suppose so, but we don't want bots :( All metrics will get skewed and we won't know who is a bot and who isn't. It is also fun to check what people are uploading
